name: Go

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./cmd/main.go

    - name: Test
      run: |
        mkdir coverage
        go test -v -coverprofile=coverage/coverage.out.tmp -json ./... > test-results.json
        grep -v "mock_" coverage/coverage.out.tmp > coverage/coverage.out
        rm coverage/coverage.out.tmp
        go tool cover -html=coverage/coverage.out -o=coverage/coverage.html

    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
       name: test-results.json
       path: test-results.json

    - name: Upload Go coverage results
      uses: actions/upload-artifact@v4
      with:
       name: coverage.html
       path: coverage/coverage.html

        
        
